// client/src/components/TypingTest.vue
<template>
  <div class="min-h-screen flex flex-col items-center py-8 px-4">
    <!-- Header -->
    <header class="w-full max-w-4xl text-center mb-6">
      <h1 class="text-3xl font-bold text-primary mb-2">Chaotic Type Speed Test</h1>
      <p class="text-lg text-gray-600">Type accurately as the keyboard scrambles after each keystroke!</p>
    </header>

    <!-- Main Content -->
    <main class="w-full max-w-4xl flex flex-col items-center space-y-8">
      <!-- Stats Bar -->
      <stats-bar
        :time="formatTime(elapsedTime)"
        :wpm="wpm"
        :accuracy="accuracy"
        :keystrokes="keystrokes"
      />

      <!-- Text Display Area -->
      <div class="w-full bg-white rounded-lg shadow-md p-6 mb-4 relative">
        <div class="typing-text text-lg leading-relaxed whitespace-pre-wrap">
          <span 
            v-for="(char, index) in currentText" 
            :key="index" 
            :class="{
              'character-current': index === currentPosition,
              'character-correct': index < currentPosition && typedChars[index] === char,
              'character-incorrect': index < currentPosition && typedChars[index] !== char
            }"
          >
            {{ char }}
          </span>
        </div>

        <!-- Progress bar -->
        <div class="w-full h-1 bg-gray-200 rounded-full mt-6 overflow-hidden">
          <div 
            class="h-full bg-primary rounded-full transition-all duration-300" 
            :style="`width: ${progress}%`"
          ></div>
        </div>
      </div>

      <!-- Control Buttons -->
      <div class="flex space-x-4 mb-6">
        <button 
          class="px-6 py-2 bg-primary hover:bg-primary/90 text-white font-medium rounded-md shadow transition"
          @click="startTest"
          :disabled="isTestActive"
          :class="{ 'opacity-50 cursor-not-allowed': isTestActive }"
        >
          Start Test
        </button>
        <button 
          class="px-6 py-2 bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium rounded-md shadow transition"
          @click="resetTest"
          :disabled="!isTestActive && !testComplete"
          :class="{ 'opacity-50 cursor-not-allowed': !isTestActive && !testComplete }"
        >
          Reset
        </button>
      </div>

      <!-- Keyboard Visualization -->
      <keyboard 
        v-if="!testComplete"
        :keyboard-layout="keyboardLayout"
        :current-key="currentKey"
      />

      <!-- Results Card -->
      <results-card
        v-if="testComplete"
        :wpm="wpm"
        :accuracy="accuracy"
        :time="formatTime(elapsedTime)"
        :chars="correctKeystrokes"
        @try-again="resetTest"
      />
    </main>

    <!-- Footer -->
    <footer class="w-full max-w-4xl mt-auto pt-8 text-center text-gray-500 text-sm">
      <p>Chaotic Type Speed Test | Challenge your typing skills with a constantly scrambling keyboard!</p>
    </footer>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted, onUnmounted } from 'vue';
import Keyboard from './Keyboard.vue';
import StatsBar from './StatsBar.vue';
import ResultsCard from './ResultsCard.vue';
import { typingTexts } from '../constants/typingTexts';
import { scrambleKeyboard } from '../utils/keyboard';
import { KeyboardLayout } from '../types/typing';

export default defineComponent({
  name: 'TypingTest',
  components: {
    Keyboard,
    StatsBar,
    ResultsCard
  },
  setup() {
    // State variables
    const currentTextIndex = ref(0);
    const isTestActive = ref(false);
    const startTime = ref<Date | null>(null);
    const elapsedTime = ref(0);
    const keystrokes = ref(0);
    const correctKeystrokes = ref(0);
    const wpm = ref(0);
    const accuracy = ref(100);
    const currentPosition = ref(0);
    const testComplete = ref(false);
    const timerInterval = ref<number | null>(null);
    const currentKey = ref('');
    const typedChars = ref<string[]>([]);

    // Initial keyboard layout
    const keyboardLayout = ref<KeyboardLayout>({
      row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
      row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
      row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
    });

    // Computed properties
    const currentText = computed(() => {
      return typingTexts[currentTextIndex.value].split('');
    });

    const progress = computed(() => {
      return (currentPosition.value / currentText.value.length) * 100;
    });

    // Methods
    const startTest = () => {
      isTestActive.value = true;
      currentPosition.value = 0;
      keystrokes.value = 0;
      correctKeystrokes.value = 0;
      accuracy.value = 100;
      wpm.value = 0;
      startTime.value = null;
      testComplete.value = false;
      elapsedTime.value = 0;
      typedChars.value = [];
      
      // Reset keyboard to normal layout
      keyboardLayout.value = {
        row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
        row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
        row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
      };
      
      // Focus the window to capture keystrokes
      window.focus();
    };

    const resetTest = () => {
      isTestActive.value = false;
      currentPosition.value = 0;
      keystrokes.value = 0;
      correctKeystrokes.value = 0;
      accuracy.value = 100;
      wpm.value = 0;
      startTime.value = null;
      testComplete.value = false;
      elapsedTime.value = 0;
      typedChars.value = [];
      
      // Reset keyboard to normal layout
      keyboardLayout.value = {
        row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
        row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
        row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
      };
      
      // Stop timer
      if (timerInterval.value) {
        clearInterval(timerInterval.value);
        timerInterval.value = null;
      }
    };

    const startTimer = () => {
      if (timerInterval.value) {
        clearInterval(timerInterval.value);
      }
      
      timerInterval.value = window.setInterval(() => {
        if (!isTestActive.value || testComplete.value) {
          if (timerInterval.value) {
            clearInterval(timerInterval.value);
            timerInterval.value = null;
          }
          return;
        }
        
        if (startTime.value) {
          elapsedTime.value = new Date().getTime() - startTime.value.getTime();
          
          // Update WPM (5 characters = 1 word)
          const elapsedMinutes = elapsedTime.value / 60000;
          if (elapsedMinutes > 0) {
            wpm.value = Math.floor((correctKeystrokes.value / 5) / elapsedMinutes);
          }
        }
      }, 1000);
    };

    const formatTime = (ms: number) => {
      const minutes = Math.floor(ms / 60000);
      const seconds = Math.floor((ms % 60000) / 1000);
      return `${minutes}:${seconds.toString().padStart(2, '0')}`;
    };

    const completeTest = () => {
      isTestActive.value = false;
      testComplete.value = true;
      
      // Stop timer
      if (timerInterval.value) {
        clearInterval(timerInterval.value);
        timerInterval.value = null;
      }
    };

    const handleKeyPress = (event: KeyboardEvent) => {
      if (!isTestActive.value) return;
      
      // Get expected character and pressed character
      const expectedChar = currentText.value[currentPosition.value];
      const pressedChar = event.key;
      
      // Store current key for keyboard highlighting
      currentKey.value = pressedChar.toUpperCase();
      
      // Start timer on first keystroke
      if (currentPosition.value === 0 && startTime.value === null) {
        startTime.value = new Date();
        startTimer();
      }
      
      // Store typed character
      typedChars.value[currentPosition.value] = pressedChar;
      
      // Check if the pressed key is correct
      if (pressedChar === expectedChar) {
        correctKeystrokes.value++;
        
        // Move to next character
        currentPosition.value++;
        
        // Check if typing is complete
        if (currentPosition.value >= currentText.value.length) {
          completeTest();
          return;
        }
      }
      
      // Count keystroke
      keystrokes.value++;
      
      // Update accuracy
      accuracy.value = Math.floor((correctKeystrokes.value / keystrokes.value) * 100);
      
      // Update WPM (5 characters = 1 word)
      if (startTime.value) {
        const elapsedMinutes = (new Date().getTime() - startTime.value.getTime()) / 60000;
        if (elapsedMinutes > 0) {
          wpm.value = Math.floor((correctKeystrokes.value / 5) / elapsedMinutes);
        }
      }
      
      // Scramble keyboard after every keystroke
      keyboardLayout.value = scrambleKeyboard(keyboardLayout.value);
    };

    // Set up and clean up event listeners
    onMounted(() => {
      document.addEventListener('keydown', handleKeyPress);
    });
    
    onUnmounted(() => {
      document.removeEventListener('keydown', handleKeyPress);
      if (timerInterval.value) {
        clearInterval(timerInterval.value);
      }
    });

    return {
      currentTextIndex,
      isTestActive,
      elapsedTime,
      keystrokes,
      correctKeystrokes,
      wpm,
      accuracy,
      currentPosition,
      testComplete,
      keyboardLayout,
      currentText,
      currentKey,
      typedChars,
      progress,
      startTest,
      resetTest,
      formatTime
    };
  }
});
</script>

<style scoped>
.typing-text {
  font-family: 'Roboto Mono', monospace;
}
.character-correct {
  color: hsl(var(--correct, 142 76% 36%));
}
.character-incorrect {
  color: hsl(var(--destructive));
  text-decoration: underline;
}
.character-current {
  background-color: rgba(63, 81, 181, 0.2);
  border-left: 2px solid hsl(var(--primary));
  animation: blink 1s infinite;
}
@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.7; }
}
</style>

// client/src/components/TypingTest.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import Keyboard from './Keyboard';
import StatsBar from './StatsBar';
import ResultsCard from './ResultsCard';
import { typingTexts } from '../constants/typingTexts';
import { scrambleKeyboard } from '../utils/keyboard';
import { KeyboardLayout } from '../types/typing';
import { formatTime } from '../utils/typingStats';

const TypingTest = () => {
  // State variables
  const [currentTextIndex, setCurrentTextIndex] = useState(0);
  const [isTestActive, setIsTestActive] = useState(false);
  const [startTime, setStartTime] = useState<Date | null>(null);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [keystrokes, setKeystrokes] = useState(0);
  const [correctKeystrokes, setCorrectKeystrokes] = useState(0);
  const [wpm, setWpm] = useState(0);
  const [accuracy, setAccuracy] = useState(100);
  const [currentPosition, setCurrentPosition] = useState(0);
  const [testComplete, setTestComplete] = useState(false);
  const [currentKey, setCurrentKey] = useState('');
  const [typedChars, setTypedChars] = useState<string[]>([]);
  const [isShiftPressed, setIsShiftPressed] = useState(false);
  const timerIntervalRef = useRef<number | null>(null);

  // Initial keyboard layout
  const [keyboardLayout, setKeyboardLayout] = useState<KeyboardLayout>({
    row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
    row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
    row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
  });
  
  // Flag to track if keyboard has been scrambled yet
  const [keyboardScrambled, setKeyboardScrambled] = useState<boolean>(false);

  // Current text and progress calculations
  const currentText = typingTexts[currentTextIndex].split('');
  const progress = (currentPosition / currentText.length) * 100;

  // Reset and initialize the test
  const resetTest = () => {
    // Reset everything first
    setCurrentPosition(0);
    setKeystrokes(0);
    setCorrectKeystrokes(0);
    setAccuracy(100);
    setWpm(0);
    setStartTime(null);
    setTestComplete(false);
    setElapsedTime(0);
    setTypedChars([]);
    setPreviousLayouts([]);
    setCorrectedChars([]);
    
    // Reset keyboard to normal layout
    setKeyboardLayout({
      row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
      row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
      row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
    });
    
    // Stop any existing timer
    if (timerIntervalRef.current) {
      clearInterval(timerIntervalRef.current);
      timerIntervalRef.current = null;
    }
    
    // Reset test status but leave it inactive until first keystroke
    setIsTestActive(false);
    setKeyboardScrambled(false);
    
    // Focus the window to capture keystrokes
    window.focus();
  };
  
  // Start the test manually
  const startTest = () => {
    resetTest();
    setIsTestActive(true);
  };
  
  // Auto-start test when keypress is detected
  const autoStartTest = useCallback(() => {
    if (!isTestActive) {
      setIsTestActive(true);
    }
  }, [isTestActive]);

  // Start the timer for the test
  const startTimer = useCallback(() => {
    if (timerIntervalRef.current) {
      clearInterval(timerIntervalRef.current);
    }
    
    // Define a reference point for time calculation
    const timeStarted = new Date();
    setStartTime(timeStarted);
    
    timerIntervalRef.current = window.setInterval(() => {
      if (!isTestActive || testComplete) {
        if (timerIntervalRef.current) {
          clearInterval(timerIntervalRef.current);
          timerIntervalRef.current = null;
        }
        return;
      }
      
      // Update elapsed time directly from the reference point
      const newElapsedTime = new Date().getTime() - timeStarted.getTime();
      setElapsedTime(newElapsedTime);
      
      // Update WPM (5 characters = 1 word)
      const elapsedMinutes = newElapsedTime / 60000;
      if (elapsedMinutes > 0) {
        setWpm(Math.floor((correctKeystrokes / 5) / elapsedMinutes));
      }
    }, 100); // Update more frequently for smoother time display
  }, [correctKeystrokes, isTestActive, testComplete]);

  // Complete the test
  const completeTest = () => {
    setIsTestActive(false);
    setTestComplete(true);
    
    // Stop timer
    if (timerIntervalRef.current) {
      clearInterval(timerIntervalRef.current);
      timerIntervalRef.current = null;
    }
  };

  // Find the position of a key in the keyboard layout
  const findKeyPosition = useCallback((layout: KeyboardLayout, char: string): { row: number, index: number } | null => {
    char = char.toUpperCase();
    
    // Check row 1
    const row1Index = layout.row1.indexOf(char);
    if (row1Index !== -1) {
      return { row: 1, index: row1Index };
    }
    
    // Check row 2
    const row2Index = layout.row2.indexOf(char);
    if (row2Index !== -1) {
      return { row: 2, index: row2Index };
    }
    
    // Check row 3
    const row3Index = layout.row3.indexOf(char);
    if (row3Index !== -1) {
      return { row: 3, index: row3Index };
    }
    
    return null;
  }, []);
  
  // Map physical keyboard key to virtual keyboard letter
  const mapPhysicalKeyToVirtual = useCallback((physicalKey: string, layout: KeyboardLayout): string => {
    // Convert to uppercase for position finding
    const upperPhysicalKey = physicalKey.toUpperCase();
    
    // Standard QWERTY keyboard layout
    const qwertyLayout = {
      row1: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
      row2: ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
      row3: ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
    };
    
    // Find position of physical key on standard keyboard
    const physicalKeyPosition = findKeyPosition(qwertyLayout, upperPhysicalKey);
    
    // If key not found or not a letter key, return original key
    if (!physicalKeyPosition || !/^[A-Z]$/i.test(upperPhysicalKey)) {
      return physicalKey;
    }
    
    // Get the letter at the same position in the scrambled layout
    let virtualKey = '';
    if (physicalKeyPosition.row === 1) {
      virtualKey = layout.row1[physicalKeyPosition.index] || upperPhysicalKey;
    } else if (physicalKeyPosition.row === 2) {
      virtualKey = layout.row2[physicalKeyPosition.index] || upperPhysicalKey;
    } else if (physicalKeyPosition.row === 3) {
      virtualKey = layout.row3[physicalKeyPosition.index] || upperPhysicalKey;
    }
    
    // Apply case based on shift state
    if (isShiftPressed) {
      return virtualKey.toUpperCase();
    } else {
      return virtualKey.toLowerCase();
    }
  }, [findKeyPosition, isShiftPressed]);

  // Process key press events
  const handleKeyPress = useCallback((event: KeyboardEvent) => {
    if (!isTestActive) return;
    
    // Get the expected character
    const expectedChar = currentText[currentPosition];
    
    // Get the physical key pressed
    const physicalKey = event.key;
    
    // Check if this is an A-Z key (for scrambling purposes)
    const isAlphaKey = /^[a-zA-Z]$/i.test(physicalKey);
    
    // Map physical keyboard key to virtual keyboard letter
    const mappedKey = mapPhysicalKeyToVirtual(physicalKey, keyboardLayout);
    
    // Key used for input comparison
    const pressedChar = mappedKey;
    
    // Store current key for keyboard highlighting (show physical key)
    setCurrentKey(physicalKey.toUpperCase());
    
    // Start timer on first keystroke
    if (currentPosition === 0 && startTime === null) {
      setStartTime(new Date());
      startTimer();
    }
    
    // Store typed character
    const newTypedChars = [...typedChars];
    newTypedChars[currentPosition] = pressedChar;
    setTypedChars(newTypedChars);
    
    // Count keystroke
    setKeystrokes(prev => prev + 1);
    
    // Check if input is correct
    const isCorrect = pressedChar === expectedChar;
    
    // If correct, increment correct keystroke count
    if (isCorrect) {
      setCorrectKeystrokes(prev => prev + 1);
    }
    
    // Always move to next character regardless of correctness
    setCurrentPosition(prev => prev + 1);
    
    // Check if typing is complete
    if (currentPosition + 1 >= currentText.length) {
      completeTest();
      return;
    }
    
    // Update accuracy
    const newKeystrokes = keystrokes + 1;
    const newAccuracy = Math.floor((correctKeystrokes + (isCorrect ? 1 : 0)) / newKeystrokes * 100);
    setAccuracy(newAccuracy);
    
    // Update WPM (5 characters = 1 word)
    if (startTime) {
      const elapsedMinutes = (new Date().getTime() - startTime.getTime()) / 60000;
      if (elapsedMinutes > 0) {
        const newCorrectKeystrokes = correctKeystrokes + (isCorrect ? 1 : 0);
        setWpm(Math.floor((newCorrectKeystrokes / 5) / elapsedMinutes));
      }
    }
    
    // Only scramble keyboard layout after A-Z keys are pressed
    if (isAlphaKey) {
      // Store current layout before scrambling
      setPreviousLayouts(prev => [...prev, {...keyboardLayout}]);
      
      // Scramble the keyboard
      setKeyboardLayout(scrambleKeyboard(keyboardLayout));
    }
  }, [
    correctKeystrokes, 
    currentPosition, 
    currentText, 
    isTestActive, 
    keyboardLayout, 
    keystrokes, 
    startTime, 
    startTimer, 
    typedChars,
    mapPhysicalKeyToVirtual
  ]);
  
  // Store previous keyboard layouts to enable backspace
  const [previousLayouts, setPreviousLayouts] = useState<KeyboardLayout[]>([]);
  const [correctedChars, setCorrectedChars] = useState<boolean[]>([]);

  // Handle key down events
  const handleKeyDown = useCallback((event: KeyboardEvent) => {
    // Auto-start test when a regular key is pressed
    if (!isTestActive && !testComplete) {
      const isRegularKey = /^[a-zA-Z0-9]$/i.test(event.key);
      if (isRegularKey) {
        // Start test with a clean state
        setIsTestActive(true);
      }
    }
    
    // Don't process further if test isn't active
    if (!isTestActive) return;
    
    // Track shift key state
    if (event.key === 'Shift') {
      setIsShiftPressed(true);
      return; // Don't process Shift key as input
    }
    
    // Also update shift state from the shiftKey property
    if (event.shiftKey) {
      setIsShiftPressed(true);
    }
    
    // Handle backspace
    if (event.key === 'Backspace') {
      // Only allow backspace if we're not at the beginning
      if (currentPosition > 0) {
        // Move cursor back
        setCurrentPosition(prev => prev - 1);
        
        // Mark this position as corrected if it was initially wrong and is now being fixed
        const expectedChar = currentText[currentPosition - 1];
        const typedChar = typedChars[currentPosition - 1];
        const wasWrong = typedChar !== expectedChar;
        
        if (wasWrong) {
          const newCorrected = [...correctedChars];
          newCorrected[currentPosition - 1] = true;
          setCorrectedChars(newCorrected);
        }
        
        // Restore previous keyboard layout if available
        if (previousLayouts.length > 0) {
          const prevLayouts = [...previousLayouts];
          const lastLayout = prevLayouts.pop();
          if (lastLayout) {
            setKeyboardLayout(lastLayout);
            setPreviousLayouts(prevLayouts);
          }
        }
      }
      
      // Don't process further
      return;
    }
    
    // Process regular keypress
    handleKeyPress(event);
  }, [handleKeyPress, isTestActive, testComplete, currentPosition, currentText, typedChars, previousLayouts]);
  
  // Handle key up events
  const handleKeyUp = useCallback((event: KeyboardEvent) => {
    // Track shift key state
    if (event.key === 'Shift') {
      setIsShiftPressed(false);
    }
    
    // Check shift key state
    if (!event.shiftKey) {
      setIsShiftPressed(false);
    }
  }, []);
  
  // Set up and clean up event listeners
  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);
    
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
      if (timerIntervalRef.current) {
        clearInterval(timerIntervalRef.current);
      }
    };
  }, [handleKeyDown, handleKeyUp]);

  return (
    <div className="min-h-screen flex flex-col items-center py-8 px-4">
      {/* Header */}
      <header className="w-full max-w-4xl text-center mb-6">
        <h1 className="text-3xl font-bold text-primary mb-2">Chaotic Typing Speed Test</h1>
        <p className="text-lg text-gray-600">Type accurately as the keyboard scrambles after each keystroke!</p>
      </header>

      {/* Main Content */}
      <main className="w-full max-w-4xl flex flex-col items-center space-y-8">
        {/* Stats Bar */}
        <StatsBar
          time={formatTime(elapsedTime)}
          wpm={wpm}
          accuracy={accuracy}
          keystrokes={keystrokes}
        />

        {/* Text Display Area */}
        <div className="w-full bg-white rounded-lg shadow-md p-6 mb-4 relative">
          <div className="typing-text text-lg leading-relaxed whitespace-pre-wrap">
            {currentText.map((char, index) => (
              <span 
                key={index} 
                className={
                  index === currentPosition
                    ? 'character-current'
                    : index < currentPosition && typedChars[index] === char
                    ? 'character-correct'
                    : index < currentPosition && typedChars[index] !== char && correctedChars[index]
                    ? 'character-corrected'
                    : index < currentPosition && typedChars[index] !== char
                    ? 'character-incorrect'
                    : ''
                }
              >
                {char}
              </span>
            ))}
          </div>

          {/* Progress bar */}
          <div className="w-full h-1 bg-gray-200 rounded-full mt-6 overflow-hidden">
            <div 
              className="h-full bg-primary rounded-full transition-all duration-300" 
              style={{ width: `${progress}%` }}
            ></div>
          </div>
        </div>

        {/* Control Buttons */}
        <div className="flex space-x-4 mb-6">
          <button 
            className={`px-6 py-2 bg-primary hover:bg-primary/90 text-white font-medium rounded-md shadow transition ${isTestActive ? 'opacity-50 cursor-not-allowed' : ''}`}
            onClick={startTest}
            disabled={isTestActive}
          >
            Start Test
          </button>
          <button 
            className={`px-6 py-2 bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium rounded-md shadow transition ${(!isTestActive && !testComplete && keystrokes === 0) ? 'opacity-50 cursor-not-allowed' : ''}`}
            onClick={resetTest}
            disabled={!isTestActive && !testComplete && keystrokes === 0}
          >
            Reset
          </button>
        </div>

        {/* Keyboard Visualization or Results Card */}
        {!testComplete ? (
          <Keyboard 
            keyboardLayout={keyboardLayout}
            currentKey={currentKey}
          />
        ) : (
          <ResultsCard
            wpm={wpm}
            accuracy={accuracy}
            time={formatTime(elapsedTime)}
            chars={correctKeystrokes}
            onTryAgain={resetTest}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="w-full max-w-4xl mt-auto pt-8 text-center text-gray-500 text-sm">
        <p>Chaotic Typing Speed Test | Challenge your typing skills with a constantly scrambling keyboard!</p>
      </footer>
    </div>
  );
};

export default TypingTest;
